version: '3'
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    # environment:
    #   - REACT_APP_NAME="App Project"
    #   - REACT_APP_API_HOST:"http://localhost:8000/api/v1"
    env_file:
      - ./.env.prod
