# build environment
FROM node:18.1.0-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_NAME="App Project Prod"
RUN npm run build
#ENV REACT_APP_NAME="App Project React"
#RUN npm run build


FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf